application: binman-norwich
version: 1
runtime: python
api_version: 1

handlers:


- url: /_ah/mail/sms@binman-norwich.appspotmail\.com
  script: handle_incoming_email.py 
  login: admin
  
- url: /.*
  script: taykt_handler.py

inbound_services:
- mail